### ISSUE TITLE
App icons are blank from iOS9

### ISSUE THREAD

**Issue by umekun123** [danielamitay/DAAppsViewController#28]
Hi, I like this library very much, but from iOS9, it seems that all app icons are not displayed properly, they are all blank icons now.  Any way to fix it?

**Comment by aaru** [comment]
Entire screen is blank if i test it on iOS 9 device. But it works perfectly fine on Simulator.
Even the demo code shows blank screen on Device, but works on simulator.

**Comment by danielamitay** [comment]
Hey @umekun123, this issue was due to the App Transport Security Settings introduced in iOS 9.0. Unfortunately Apple's image resources are returned with HTTP, so an exception is necessary. See the [relevant README section](https://github.com/danielamitay/DAAppsViewController#app-transport-security-settings) for information on doing so in your app.
